import Icon from "@/components/Icon";

export type Genre =
  | "accounting"
  | "ads"
  | "analytics"
  | "ats"
  | "calendar"
  | "cdn"
  | "cms"
  | "crm"
  | "design"
  | "devtools"
  | "dns"
  | "documentation"
  | "ecommerce"
  | "email"
  | "everything"
  | "form"
  | "gdpr"
  | "hosting"
  | "marketing"
  | "monitoring"
  | "open_web"
  | "payments"
  | "podcast"
  | "search"
  | "security"
  | "social_media"
  | "static_site_generator"
  | "support"
  | "videos"
  | "web_framework";

export const GENRE_REGISTRY: {
  [key in Genre]: {
    name: string;
    description: string;
  };
} = {
  static_site_generator: {
    name: "Static Site Generator",
    description: "Static site generators",
  },
  devtools: {
    name: "Developer Tools",
    description: "Developer tools",
  },
  ads: {
    name: "Advertising",
    description: "Advertising services",
  },
  open_web: {
    name: "Open Web",
    description: "Open web services",
  },
  search: {
    name: "Search",
    description: "Search services",
  },
  accounting: {
    name: "Accounting",
    description: "Accounting services",
  },
  analytics: {
    name: "Analytics",
    description: "Tools for tracking and analyzing website or app usage",
  },
  ats: {
    name: "Applicant Tracking System",
    description: "Software for managing recruitment processes",
  },
  calendar: {
    name: "Calendar",
    description: "Tools for scheduling and managing events",
  },
  cdn: {
    name: "Content Delivery Network",
    description: "Services for distributing content globally",
  },
  cms: {
    name: "Content Management System",
    description: "Platforms for creating and managing digital content",
  },
  crm: {
    name: "Customer Relationship Management",
    description: "Systems for managing customer interactions and data",
  },
  design: {
    name: "Design",
    description: "Tools for graphic and web design",
  },
  dns: {
    name: "Domain Name System",
    description: "Services for managing domain names and DNS records",
  },
  documentation: {
    name: "Documentation",
    description: "Tools for creating and managing technical documentation",
  },
  ecommerce: {
    name: "E-commerce",
    description: "Platforms for online selling and shopping",
  },
  email: {
    name: "Email",
    description: "Services for email hosting and management",
  },
  everything: {
    name: "Everything",
    description: "Comprehensive platforms covering multiple categories",
  },
  form: {
    name: "Form",
    description: "Tools for creating and managing online forms",
  },
  gdpr: {
    name: "GDPR Compliance",
    description:
      "Services for ensuring compliance with data protection regulations",
  },
  hosting: {
    name: "Hosting",
    description: "Services for hosting websites and applications",
  },
  marketing: {
    name: "Marketing",
    description: "Tools for digital marketing and promotion",
  },
  monitoring: {
    name: "Monitoring",
    description: "Services for tracking system performance and uptime",
  },
  payments: {
    name: "Payments",
    description: "Platforms for processing online payments",
  },
  podcast: {
    name: "Podcast",
    description: "Tools for creating and distributing podcasts",
  },
  security: {
    name: "Security",
    description: "Services for enhancing online security and protection",
  },
  social_media: {
    name: "Social Media",
    description: "Platforms for social networking and content sharing",
  },
  support: {
    name: "Support",
    description: "Tools for customer support and helpdesk management",
  },
  videos: {
    name: "Videos",
    description: "Platforms for hosting and streaming video content",
  },
  web_framework: {
    name: "Web Framework",
    description: "Frameworks for building web applications",
  },
};

type Service = {
  identifier: string;
  name: string;
  genre: Genre;
  url: string;
  icon?: React.ReactNode;
  cname_values?: string[];
  mx_values?: string[];
  ns_values?: string[];
  txt_values?: string[];
  spf_values?: string[];
  urlSubstrings?: string[];
  substrings?: string[];
  defunct?: boolean;
  headers?: {
    [key: string]: string;
  };
};

export const REGISTRY: {
  [key: string]: Service;
} = {
  webex: {
    identifier: "webex",
    name: "Webex",
    genre: "hosting",
    url: "https://www.webex.com",
    txt_values: ["webexdomainverification"],
  },
  liveramp: {
    identifier: "liveramp",
    name: "Liveramp",
    genre: "marketing",
    url: "https://liveramp.com",
    txt_values: ["liveramp-site-verification"],
  },
  paloalto: {
    identifier: "paloalto",
    name: "Palo Alto",
    genre: "security",
    url: "https://www.paloaltonetworks.com",
    txt_values: ["paloaltonetworks-site-verification"],
  },
  headway: {
    identifier: "headway",
    name: "Headway",
    genre: "support",
    url: "https://headwayapp.co",
    cname_values: ["headwayapp.co"],
  },
  skysnag: {
    identifier: "skysnag",
    name: "Skysnag",
    genre: "security",
    url: "https://skysnag.com",
    spf_values: ["_spf.skysnag.com"],
  },
  constantcontact: {
    identifier: "constantcontact",
    name: "Constant Contact",
    genre: "marketing",
    url: "https://www.constantcontact.com",
    substrings: ["constantcontact.com"],
    spf_values: ["spf.constantcontact.com"],
  },
  rss: {
    identifier: "rss",
    name: "RSS",
    genre: "open_web",
    url: "https://rss.com",
  },
  readme: {
    identifier: "readme",
    name: "ReadMe",
    genre: "documentation",
    url: "https://readme.com",
    cname_values: ["ssl.readmessl.com"],
  },
  formassembly: {
    identifier: "formassembly",
    name: "FormAssembly",
    genre: "crm",
    url: "https://formassembly.com",
    spf_values: ["spf1.formassembly.com"],
  },
  fireside: {
    identifier: "fireside",
    name: "Fireside",
    genre: "podcast",
    url: "https://fireside.fm",
    cname_values: ["hosted.fireside.fm"],
  },
  geojs: {
    identifier: "geojs",
    name: "GeoJS",
    genre: "analytics",
    url: "https://geojs.io",
    substrings: ["geojs.io/v1"],
  },
  digitalocean: {
    identifier: "digitalocean",
    name: "DigitalOcean",
    genre: "hosting",
    url: "https://www.digitalocean.com",
    ns_values: ["ns1.digitalocean.com", "ns2.digitalocean.com"],
  },
  github_pages: {
    identifier: "github_pages",
    name: "GitHub Pages",
    genre: "hosting",
    url: "https://pages.github.com",
    cname_values: ["pages.github.com"],
  },
  gitbook: {
    identifier: "gitbook",
    name: "GitBook",
    genre: "hosting",
    url: "https://www.gitbook.com",
    cname_values: ["gitbook.io"],
  },
  substack: {
    identifier: "substack",
    name: "Substack",
    url: "https://www.substack.com",
    genre: "email",
    cname_values: ["substack-custom-domains.com"],
  },
  datadog: {
    identifier: "datadog",
    name: "Datadog",
    url: "https://www.datadoghq.com",
    genre: "monitoring",
    substrings: ["function(h,o,u,n,d)"],
  },
  umami: {
    identifier: "umami",
    name: "Umami",
    url: "https://umami.is",
    genre: "analytics",
    cname_values: ["umami.sh"],
    substrings: ["data-website-id"],
  },
  nolt: {
    identifier: "nolt",
    name: "Nolt",
    url: "https://nolt.io",
    genre: "support",
    cname_values: ["custom-domain.nolt.io"],
  },
  improv_mx: {
    identifier: "improv_mx",
    name: "ImprovMX",
    url: "https://www.improvmx.com",
    genre: "email",
    mx_values: ["mx1.improvmx.com"],
  },
  proofpoint: {
    identifier: "proofpoint",
    name: "Proofpoint",
    url: "https://www.proofpoint.com",
    genre: "security",
    mx_values: ["pphosted.com"],
  },
  namecheap: {
    identifier: "namecheap",
    name: "Namecheap",
    url: "https://www.namecheap.com",
    genre: "dns",
    ns_values: [
      "ns1.namecheap.com",
      "ns2.namecheap.com",
      "ns3.namecheap.com",
      "ns4.namecheap.com",
    ],
    spf_values: [
      "spf.efwd.registrar-servers.com",
      "spf.web-hosting.com",
      "privateemail.com",
    ],
  },
  fastmail: {
    identifier: "fastmail",
    name: "FastMail",
    url: "https://www.fastmail.com",
    genre: "email",
    mx_values: ["smtp.messagingengine.com"],
    spf_values: ["spf.messagingengine.com"],
  },
  sailthru: {
    identifier: "sailthru",
    name: "Sailthru",
    url: "https://www.sailthru.com",
    genre: "marketing",
    spf_values: ["aspmx.sailthru.com"],
  },
  dnsimple: {
    identifier: "dnsimple",
    name: "DNSimple",
    url: "https://www.dnsimple.com",
    genre: "dns",
    ns_values: ["dnsimple.com"],
  },
  vercel: {
    identifier: "vercel",
    name: "Vercel",
    url: "https://www.vercel.com",
    genre: "hosting",
    ns_values: ["vercel-dns.com"],
  },
  wix: {
    identifier: "wix",
    name: "Wix",
    url: "https://www.wix.com",
    genre: "hosting",
    ns_values: ["wixdns.net"],
    substrings: ["Wix.com Website Builder"],
    cname_values: ["wixdns.net"],
  },
  zoho_invoices: {
    identifier: "zoho_invoices",
    name: "Zoho Invoices",
    url: "https://www.zoho.com/invoices",
    genre: "accounting",
    spf_values: ["sender.zohoinvoice.com"],
  },
  drip: {
    identifier: "drip",
    name: "Drip",
    url: "https://www.drip.com",
    genre: "email",
    substrings: ["data-drip"],
  },
  zoho_campaigns: {
    identifier: "zoho_campaigns",
    name: "Zoho Campaigns",
    url: "https://www.zoho.com/campaigns",
    genre: "marketing",
    substrings: ["zcc.zoho.com"],
  },
  zoho_mail: {
    identifier: "zoho_mail",
    name: "Zoho Mail",
    url: "https://www.zoho.com/mail",
    genre: "email",
    mx_values: ["mx.zoho.com"],
    spf_values: ["zoho.com", "zeptomail.net"],
  },
  elasticemail: {
    identifier: "elasticemail",
    name: "ElasticEmail",
    url: "https://www.elasticemail.com",
    genre: "email",
    spf_values: ["_spf.elasticemail.com"],
  },
  aws_s3: {
    identifier: "aws_s3",
    name: "AWS S3",
    url: "https://aws.amazon.com/s3",
    genre: "hosting",
    substrings: ["s3.amazonaws.com", "NoSuchBucket"],
  },
  aws_ses: {
    identifier: "aws_ses",
    name: "AWS SES",
    url: "https://aws.amazon.com/ses",
    genre: "email",
    spf_values: ["amazonses.com"],
  },
  carbon: {
    identifier: "carbon",
    name: "Carbon",
    url: "https://carbonads.net",
    genre: "ads",
    substrings: ["https://cdn.carbonads.com/carbon.js"],
  },
  rocket: {
    identifier: "rocket",
    name: "Rocket",
    url: "https://rocket.net",
    genre: "hosting",
    cname_values: ["onrocket.site"],
  },
  woocommerce: {
    identifier: "woocommerce",
    name: "WooCommerce",
    url: "https://woocommerce.com",
    genre: "ecommerce",
    substrings: ["woocommerce_params"],
  },
  aws_cloudfront: {
    identifier: "aws_cloudfront",
    name: "AWS CloudFront",
    url: "https://aws.amazon.com/cloudfront/",
    genre: "cdn",
  },
  google_analytics: {
    identifier: "google_analytics",
    name: "Google Analytics",
    genre: "analytics",
    url: "https://google.com/analytics",
    substrings: [
      "GoogleAnalyticsObject",
      "https://www.googletagmanager.com/gtag/js",
      "https://www.google-analytics.com/analytics.js",
    ],
  },
  google_adsense: {
    identifier: "google_adsense",
    name: "Google AdSense",
    genre: "marketing",
    url: "https://www.google.com/adsense",
    substrings: ["adsbygoogle.js"],
  },
  norton_safe_web: {
    identifier: "norton_safe_web",
    name: "Norton Safe Web",
    genre: "security",
    url: "https://safeweb.norton.com",
    txt_values: ["norton-safeweb-site-verification"],
  },
  cloudflare: {
    identifier: "cloudflare",
    name: "Cloudflare",
    genre: "cdn",
    url: "https://www.cloudflare.com",
    ns_values: ["cloudflare.com"],
    spf_values: ["_spf.mx.cloudflare.net"],
  },
  cloudflare_analytics: {
    identifier: "cloudflare_analytics",
    name: "Cloudflare Analytics",
    genre: "analytics",
    url: "https://www.cloudflare.com",
    substrings: ["data-cf-beacon"],
  },
  google_tag_manager: {
    identifier: "google_tag_manager",
    name: "Google Tag Manager",
    genre: "analytics",
    url: "https://tagmanager.google.com",
  },
  astro: {
    identifier: "astro",
    name: "Astro",
    genre: "web_framework",
    url: "https://astro.build",
    substrings: ["astro-slot", "/_astro"],
  },
  chargebee: {
    identifier: "chargebee",
    name: "Chargebee",
    genre: "payments",
    url: "https://www.chargebee.com",
    substrings: ["js.chargebee.com"],
  },
  mailchannels: {
    identifier: "mailchannels",
    name: "MailChannels",
    url: "https://www.mailchannels.com",
    genre: "email",
    spf_values: ["relay.mailchannels.net"],
  },
  meltwater: {
    identifier: "meltwater",
    name: "Meltwater",
    url: "https://www.meltwater.com",
    genre: "marketing",
    spf_values: ["meltwater.com"],
  },
  mailchimp: {
    identifier: "mailchimp",
    name: "Mailchimp",
    url: "https://mailchimp.com",
    genre: "email",
    substrings: ["list-manage.com", "mc:edit", "c,h,i,m,p"],
    spf_values: ["servers.mcsv.net"],
  },
  clearbit: {
    identifier: "clearbit",
    name: "Clearbit",
    url: "https://clearbit.com",
    genre: "analytics",
    substrings: ["tag.clearbitscripts"],
  },
  sparkloop: {
    identifier: "sparkloop",
    name: "SparkLoop",
    url: "https://sparkloop.app",
    genre: "email",
    substrings: ["sparkloop.app"],
  },
  tapfiliate: {
    identifier: "tapfiliate",
    name: "Tapfiliate",
    url: "https://www.tapfiliate.com",
    genre: "marketing",
    substrings: ["script.tapfiliate.com"],
  },
  rightmessage: {
    identifier: "rightmessage",
    name: "RightMessage",
    url: "https://www.rightmessage.com",
    genre: "email",
    substrings: ["rightmessage-id"],
  },
  sendowl: {
    identifier: "sendowl",
    name: "SendOwl",
    url: "https://www.sendowl.com",
    genre: "ecommerce",
    substrings: ["https://transactions.sendowl.com/assets/sendowl.js"],
  },
  sendgrid: {
    identifier: "sendgrid",
    name: "SendGrid",
    genre: "email",
    url: "https://sendgrid.com",
    spf_values: ["sendgrid.net"],
  },
  flodesk: {
    identifier: "flodesk",
    name: "Flodesk",
    genre: "email",
    url: "https://www.flodesk.com",
    substrings: ["view.flodesk.com"],
  },
  webmentions: {
    identifier: "webmentions",
    name: "Webmentions",
    genre: "social_media",
    url: "https://webmention.io",
    substrings: ['rel="webmention"'],
  },
  bluehost: {
    identifier: "bluehost",
    name: "Bluehost",
    genre: "hosting",
    url: "https://www.bluehost.com",
    cname_values: ["bluehost.com"],
  },
  bluesky: {
    identifier: "bluesky",
    name: "BlueSky",
    genre: "social_media",
    url: "https://bsky.app",
    urlSubstrings: ["bsky.app/profile"],
  },
  threads: {
    identifier: "threads",
    name: "Threads",
    genre: "social_media",
    url: "https://www.threads.net",
    urlSubstrings: ["threads.net"],
  },
  fresh: {
    identifier: "fresh",
    name: "Fresh",
    genre: "web_framework",
    url: "https://fresh.deno.dev",
    substrings: ["__frsh"],
  },
  jquery: {
    identifier: "jquery",
    name: "jQuery",
    genre: "web_framework",
    url: "https://jquery.com",
    substrings: ["jquery.com"],
  },
  mailerlite: {
    identifier: "mailerlite",
    name: "MailerLite",
    genre: "email",
    url: "https://www.mailerlite.com",
    spf_values: ["_spf.mlsend.com"],
    substrings: ["static.mailerlite.com"],
  },
  algolia: {
    identifier: "algolia",
    name: "Algolia",
    genre: "search",
    url: "https://www.algolia.com",
    substrings: ['algolia.net" crossorigin'],
  },
  bootstrap: {
    identifier: "bootstrap",
    name: "Bootstrap",
    genre: "web_framework",
    url: "https://getbootstrap.com",
    substrings: ["bootstrapcdn.com", "navbar-brand", "bootstrap.min.js"],
  },
  loom: {
    identifier: "loom",
    name: "Loom",
    genre: "videos",
    url: "https://www.loom.com",
    txt_values: ["loom-verification", "loom-site-verification"],
  },
  tailwindcss: {
    identifier: "tailwindcss",
    name: "Tailwind CSS",
    genre: "web_framework",
    url: "https://tailwindcss.com",
    substrings: ["tailwindcss.com", "mx-auto", "text-white"],
  },
  alpinejs: {
    identifier: "alpinejs",
    name: "Alpine.js",
    genre: "web_framework",
    url: "https://alpinejs.dev",
    substrings: ["x-on:click", "x-text"],
  },
  gandi: {
    identifier: "gandi",
    name: "Gandi",
    genre: "dns",
    url: "https://www.gandi.net",
    ns_values: ["ns.gandi.net"],
    spf_values: ["_mailcust.gandi.net"],
  },
  gauges: {
    identifier: "gauges",
    name: "Gauges",
    genre: "analytics",
    url: "https://www.gaug.es",
    substrings: ["gaug.es"],
  },
  mailjet: {
    identifier: "mailjet",
    name: "Mailjet",
    genre: "email",
    url: "https://www.mailjet.com",
    spf_values: ["spf.mailjet.com"],
  },
  mailersend: {
    identifier: "mailersend",
    name: "Mailersend",
    genre: "email",
    url: "https://www.mailersend.com",
    spf_values: ["_spf.mailersend.net"],
  },
  facebook_ads: {
    identifier: "facebook_ads",
    name: "Facebook Ads",
    genre: "marketing",
    url: "https://www.facebook.com/business/ads",
    txt_values: ["facebook-domain-verification"],
  },
  uservoice: {
    identifier: "uservoice",
    name: "UserVoice",
    genre: "support",
    url: "https://www.uservoice.com",
    spf_values: ["smtp1.uservoice.com"],
  },
  notion: {
    identifier: "notion",
    name: "Notion",
    genre: "design",
    url: "https://www.notion.so",
    txt_values: ["notion-domain-verification"],
  },
  customer_io: {
    identifier: "customer_io",
    name: "Customer.io",
    genre: "email",
    url: "https://www.customer.io",
    substrings: ["customerioforms"],
  },
  cloudinary: {
    identifier: "cloudinary",
    name: "Cloudinary",
    genre: "hosting",
    url: "https://www.cloudinary.com",
    substrings: ["res.cloudinary.com"],
  },
  oembed: {
    identifier: "oembed",
    name: "OEmbed",
    genre: "open_web",
    url: "https://oembed.com",
    substrings: ["json+oembed"],
  },
  statuspage: {
    identifier: "statuspage",
    name: "Statuspage",
    genre: "monitoring",
    url: "https://www.statuspage.io",
    txt_values: ["stspg-customer.com"],
  },
  facebook_pixel: {
    identifier: "facebook_pixel",
    name: "Facebook Pixel",
    genre: "analytics",
    url: "https://www.facebook.com/business/learn/facebook-ads-pixel",
    substrings: ["f.fbq"],
  },
  hackerone: {
    identifier: "hackerone",
    name: "HackerOne",
    genre: "security",
    url: "https://hackerone.com",
    txt_values: ["h1-domain-verification"],
  },
  ahrefs: {
    identifier: "ahrefs",
    name: "Ahrefs",
    genre: "marketing",
    url: "https://ahrefs.com",
    txt_values: ["ahrefs-site-verification"],
  },
  google_webmaster_tools: {
    identifier: "google_webmaster_tools",
    name: "Google Webmaster Tools",
    genre: "analytics",
    url: "https://www.google.com/webmasters/tools/home",
    txt_values: ["google-site-verification"],
  },
  senja: {
    identifier: "senja",
    name: "Senja",
    genre: "marketing",
    url: "https://www.senja.io",
    substrings: ["static.senja"],
  },
  crisp: {
    identifier: "crisp",
    name: "Crisp",
    genre: "support",
    url: "https://crisp.chat",
    substrings: ["CRISP_WEBSITE_ID"],
  },
  adestra: {
    identifier: "adestra",
    name: "Adestra",
    url: "https://www.adestra.com",
    genre: "email",
    spf_values: ["msgfocus.com"],
  },
  helpscout: {
    identifier: "helpscout",
    name: "Help Scout",
    genre: "support",
    url: "https://www.helpscout.com",
    spf_values: ["helpscoutemail.com"],
    cname_values: ["helpscoutdocs.com"],
  },
  heroku: {
    identifier: "heroku",
    name: "Heroku",
    url: "https://www.heroku.com",
    genre: "hosting",
    cname_values: ["herokudns.com"],
    headers: {
      key: "text/headers/nel",
      value: "heroku-nel",
    },
  },
  ovh: {
    identifier: "ovh",
    name: "OVH",
    url: "https://www.ovh.com",
    genre: "hosting",
    mx_values: ["mx.ovh.net"],
  },
  groove: {
    identifier: "groove",
    name: "Groove",
    url: "https://www.groovehq.com",
    genre: "support",
    substrings: [],
  },
  webflow: {
    identifier: "webflow",
    name: "Webflow",
    url: "https://www.webflow.com",
    genre: "web_framework",
    substrings: ["/js/webflow"],
    cname_values: ["proxy-ssl.webflow.com"],
    headers: {
      key: "text/headers/vary",
      value: "x-wf-forwarded-proto",
    },
  },
  loops: {
    identifier: "loops",
    name: "Loops",
    url: "https://www.loops.so",
    genre: "email",
    substrings: ["app.loops.so"],
  },
  netlify: {
    identifier: "netlify",
    name: "Netlify",
    url: "https://www.netlify.com",
    genre: "hosting",
    headers: {
      key: "text/headers/server",
      value: "Netlify",
    },
  },
  fathom: {
    identifier: "fathom",
    name: "Fathom",
    url: "https://www.usefathom.com",
    genre: "analytics",
    substrings: ["cdn.usefathom.com"],
  },
  tally: {
    identifier: "tally",
    name: "Tally",
    url: "https://www.tally.so",
    genre: "form",
    substrings: ["tally.so"],
  },
  savvycal: {
    identifier: "savvycal",
    name: "SavvyCal",
    url: "https://www.savvycal.com",
    genre: "calendar",
    substrings: ["savvycal.com"],
  },
  podia: {
    identifier: "podia",
    name: "Podia",
    url: "https://www.podia.com",
    genre: "podcast",
    cname_values: ["podia.com"],
  },
  transistor: {
    identifier: "transistor",
    name: "Transistor",
    url: "https://www.transistor.fm",
    genre: "podcast",
    substrings: [".transistor.fm"],
  },
  fastly: {
    identifier: "fastly",
    name: "Fastly",
    url: "https://www.fastly.com",
    genre: "hosting",
    txt_values: ["fastly-domain-delegation"],
  },
  postman: {
    identifier: "postman",
    name: "Postman",
    url: "https://www.postman.com",
    genre: "devtools",
    txt_values: ["postman-domain-verification"],
  },
  docker: {
    identifier: "docker",
    name: "Docker",
    url: "https://www.docker.com",
    genre: "hosting",
    txt_values: ["docker-verification"],
  },
  canva: {
    identifier: "canva",
    name: "Canva",
    url: "https://www.canva.com",
    genre: "design",
    txt_values: ["canva-domain-verification"],
  },
  rewardful: {
    identifier: "rewardful",
    name: "Rewardful",
    url: "https://www.rewardful.com",
    genre: "marketing",
    substrings: [".getrewardful.com", "data-rewardful", "window,'rewardful'"],
  },
  php: {
    identifier: "php",
    name: "PHP",
    url: "https://www.php.net",
    genre: "web_framework",
    headers: {
      key: "text/headers/set-cookie",
      value: "PHPSESSID",
    },
  },
  shopify: {
    identifier: "shopify",
    name: "Shopify",
    url: "https://www.shopify.com",
    genre: "ecommerce",
    cname_values: ["myshopify.com"],
    substrings: ["shopifycdn.com"],
    spf_values: ["shops.shopify.com"],
  },
  rails: {
    identifier: "rails",
    name: "Ruby on Rails",
    url: "https://rubyonrails.org",
    genre: "web_framework",
    substrings: ["data-turbo"],
  },
  new_relic: {
    identifier: "new_relic",
    name: "New Relic",
    url: "https://www.newrelic.com",
    genre: "monitoring",
    substrings: ["newrelic.com"],
  },
  nextjs: {
    identifier: "nextjs",
    name: "Next.js",
    url: "https://www.nextjs.org",
    genre: "web_framework",
    substrings: ["_next/static"],
  },
  klaviyo: {
    identifier: "klaviyo",
    name: "Klaviyo",
    url: "https://www.klaviyo.com",
    genre: "email",
    txt_values: ["klaviyo-site-verification"],
    substrings: ["klaviyo.init"],
    spf_values: ["klaviyomail.com"],
  },
  "101domain": {
    identifier: "101domain",
    name: "101domain",
    url: "https://www.101domain.com",
    genre: "dns",
    ns_values: ["ns1.101domain.com", "ns2.101domain.com"],
  },
  apollo: {
    identifier: "apollo",
    name: "Apollo",
    url: "https://www.apollo.io",
    genre: "analytics",
    substrings: ["assets.apollo.io"],
  },
  brevo: {
    identifier: "brevo",
    name: "Brevo",
    url: "https://www.brevo.com",
    genre: "email",
    txt_values: ["brevo-code", "Sendinblue-code"],
    substrings: ["sib_signup_form"],
    spf_values: ["spf.sendinblue.com"],
  },
  adobe: {
    identifier: "adobe",
    name: "Adobe",
    url: "https://www.adobe.com",
    genre: "design",
    txt_values: ["adobe-idp"],
  },
  namebright: {
    identifier: "namebright",
    name: "Namebright",
    url: "https://www.namebright.com",
    genre: "dns",
    spf_values: ["namebrightmail.com"],
  },
  zendesk: {
    identifier: "zendesk",
    name: "Zendesk",
    url: "https://www.zendesk.com",
    genre: "support",
    txt_values: ["mail.zendesk.com"],
    substrings: ["zdassets.com"],
    spf_values: ["mail.zendesk.com", "_spf.zdsys.com"],
  },
  paddle: {
    identifier: "paddle",
    name: "Paddle",
    url: "https://www.paddle.com",
    genre: "payments",
    txt_values: ["paddle-verification"],
  },
  stripe: {
    identifier: "stripe",
    name: "Stripe",
    url: "https://www.stripe.com",
    genre: "payments",
    txt_values: ["stripe-verification"],
    substrings: ["js.stripe.com"],
  },
  beehiiv: {
    identifier: "beehiiv",
    name: "Beehiiv",
    url: "https://www.beehiiv.com",
    genre: "marketing",
    substrings: ["beehiiv.com"],
  },
  appsflyer: {
    identifier: "appsflyer",
    name: "AppsFlyer",
    url: "https://www.appsflyer.com",
    genre: "analytics",
    cname_values: ["appsflyer.com"],
  },
  lemon_squeezy: {
    identifier: "lemon_squeezy",
    name: "Lemon Squeezy",
    url: "https://www.lemonsqueezy.com",
    genre: "payments",
    substrings: ["assets.lemonsqueezy.com"],
  },
  fly_io: {
    identifier: "fly_io",
    name: "Fly.io",
    url: "https://www.fly.io",
    genre: "hosting",
    cname_values: ["fly.dev"],
    headers: {
      key: "text/headers/fly-request-id",
      value: "*",
    },
  },
  mimecast: {
    identifier: "mimecast",
    name: "Mimecast",
    url: "https://www.mimecast.com",
    genre: "email",
    spf_values: ["eu._netblocks.mimecast.com"],
  },
  vwo: {
    identifier: "vwo",
    name: "Visual Website Optimizer",
    url: "https://www.vwo.com",
    genre: "marketing",
    substrings: ["_vwo_code"],
  },
  squarespace: {
    identifier: "squarespace",
    name: "Squarespace",
    url: "https://www.squarespace.com",
    genre: "cms",
    substrings: ["assets.squarespace.com"],
  },
  wordpress: {
    identifier: "wordpress",
    name: "WordPress",
    url: "https://www.wordpress.org",
    genre: "cms",
    substrings: ["wp-content/plugins"],
  },
  blogger: {
    identifier: "blogger",
    name: "Blogger",
    url: "https://www.blogger.com",
    genre: "cms",
    substrings: ['content="blogger" name="generator"'],
  },
  jekyll: {
    identifier: "jekyll",
    name: "Jekyll",
    url: "https://www.jekyllrb.com",
    genre: "static_site_generator",
    substrings: ['content="Jekyll'],
  },
  plausible: {
    identifier: "plausible",
    name: "Plausible",
    url: "https://www.plausible.io",
    genre: "analytics",
    substrings: ["plausible.io/js", "click.pageview.click"],
  },
  whimsical: {
    identifier: "whimsical",
    name: "Whimsical",
    url: "https://www.whimsical.com",
    genre: "design",
    txt_values: ["whimsical="],
  },
  mixpanel: {
    identifier: "mixpanel",
    name: "Mixpanel",
    url: "https://www.mixpanel.com",
    genre: "analytics",
    txt_values: ["mixpanel-domain-verify"],
  },
  microsoft_clarity: {
    identifier: "microsoft_clarity",
    name: "Microsoft Clarity",
    url: "https://www.microsoft.com",
    genre: "analytics",
    substrings: ["c,l,a,r,i,t,y"],
  },
  microsoft_365: {
    identifier: "microsoft_365",
    name: "Microsoft 365",
    url: "https://www.microsoft.com",
    genre: "everything",
    txt_values: ["v=verifydomain MS"],
  },
  buttondown: {
    identifier: "buttondown",
    name: "Buttondown",
    url: "https://www.buttondown.email",
    genre: "email",
    substrings: ["buttondown.email/"],
  },
  intercom: {
    identifier: "intercom",
    name: "Intercom",
    url: "https://www.intercom.com",
    genre: "support",
    substrings: ["intercomSettings"],
    spf_values: ["spf.mail.intercom.io"],
  },
  gatsby: {
    identifier: "gatsby",
    name: "Gatsby",
    url: "https://www.gatsbyjs.com",
    genre: "web_framework",
    substrings: ['name="generator" content="Gatsby'],
  },
  ghost: {
    identifier: "ghost",
    name: "Ghost",
    url: "https://www.ghost.org",
    genre: "cms",
    substrings: ['name="generator" content="Ghost'],
  },
  hotjar: {
    identifier: "hotjar",
    name: "Hotjar",
    url: "https://www.hotjar.com",
    genre: "analytics",
    substrings: ["h,o,t,j,a,r", "h, o, t, j, a, r)"],
  },
  drift: {
    identifier: "drift",
    name: "Drift",
    url: "https://www.drift.com",
    genre: "support",
    txt_values: ["drift-domain-verification"],
  },
  mailgun: {
    identifier: "mailgun",
    name: "Mailgun",
    url: "https://www.mailgun.com",
    genre: "email",
    spf_values: [
      "mailgun.org",
      "spf.mandrillapp.com",
      "spf1.mailgun.org",
      "spf2.mailgun.org",
    ],
  },
  campaign_monitor: {
    identifier: "campaign_monitor",
    name: "Campaign Monitor",
    url: "https://www.campaignmonitor.com",
    genre: "email",
    spf_values: ["_spf.createsend.com", "spf.createsend.com"],
    urlSubstrings: ["confirmsubscription.com"],
  },
  google: {
    identifier: "google",
    name: "Google",
    url: "https://www.google.com",
    genre: "everything",
    spf_values: ["_spf.google.com"],
  },
  rollbar: {
    identifier: "rollbar",
    name: "Rollbar",
    url: "https://www.rollbar.com",
    genre: "monitoring",
    substrings: ["_rollbarConfig"],
  },
  postmark: {
    identifier: "postmark",
    name: "Postmark",
    url: "https://www.postmarkapp.com",
    genre: "email",
    spf_values: ["mtasv.net", "spf.mtasv.net"],
  },
  posthog: {
    identifier: "posthog",
    name: "PostHog",
    url: "https://www.posthog.com",
    genre: "analytics",
    substrings: ["posthog.init"],
  },
  amplitude: {
    identifier: "amplitude",
    name: "Amplitude",
    url: "https://www.amplitude.com",
    genre: "analytics",
    substrings: ["amplitude.init", "e.amplitude"],
  },
  markmonitor: {
    identifier: "markmonitor",
    name: "MarkMonitor",
    url: "https://www.markmonitor.com",
    genre: "monitoring",
    spf_values: ["spfhost.messageprovider.com"],
  },
  marketo: {
    identifier: "marketo",
    name: "Marketo",
    url: "https://www.marketo.com",
    spf_values: ["mktomail.com"],
    substrings: ["bizible.com"],
    genre: "crm",
  },
  heymarket: {
    identifier: "heymarket",
    name: "Heymarket",
    url: "https://www.heymarket.com",
    genre: "support",
    substrings: ["heymarket.com"],
  },
  smtp2go: {
    identifier: "smtp2go",
    name: "SMTP2GO",
    url: "https://www.smtp2go.com",
    genre: "email",
    spf_values: ["spf.smtp2go.com"],
  },
  dynatrace: {
    identifier: "dynatrace",
    name: "Dynatrace",
    url: "https://www.dynatrace.com",
    genre: "monitoring",
    txt_values: ["Dynatrace-site-verification"],
  },
  salesforce: {
    identifier: "salesforce",
    name: "Salesforce",
    url: "https://www.salesforce.com",
    genre: "crm",
    spf_values: ["_spf.salesforce.com", "cust-spf.exacttarget.com"],
  },
  salesforce_marketing_cloud: {
    identifier: "salesforce_marketing_cloud",
    name: "Salesforce Marketing Cloud",
    url: "https://www.salesforce.com",
    genre: "marketing",
    txt_values: ["SMFC-"],
  },
  happyfox: {
    identifier: "happyfox",
    name: "HappyFox",
    genre: "support",
    spf_values: ["spf.happyfox.com"],
    url: "https://www.happyfox.com",
    substrings: ["HFCHAT_CONFIG"],
  },
  consider: {
    identifier: "consider",
    name: "Consider",
    url: "https://www.consider.com",
    genre: "ats",
    cname_values: ["boards.consider.com"],
  },
  svelte: {
    identifier: "svelte",
    name: "Svelte",
    url: "https://www.svelte.dev",
    genre: "web_framework",
    substrings: ["__svelte__", "__sveltekit"],
  },
  dropcatch: {
    identifier: "dropcatch",
    name: "Dropcatch",
    url: "https://www.dropcatch.com",
    genre: "dns",
    ns_values: ["ns1.dropcatch.com", "ns2.dropcatch.com"],
  },
  twitter: {
    identifier: "twitter",
    name: "Twitter",
    genre: "social_media",
    url: "https://www.twitter.com",
    icon: <Icon.Twitter className="size-6" />,
    urlSubstrings: ["twitter.com", "x.com"],
  },
  medium: {
    identifier: "medium",
    name: "Medium",
    genre: "social_media",
    url: "https://www.medium.com",
    urlSubstrings: ["medium.com"],
  },
  email_octopus: {
    identifier: "email_octopus",
    name: "EmailOctopus",
    genre: "email",
    url: "https://www.emailoctopus.com",
    spf_values: ["*.eoidentity.com"],
  },
  clicky: {
    identifier: "clicky",
    name: "Clicky",
    genre: "analytics",
    url: "https://www.clicky.com",
    substrings: ["getclicky.com"],
  },
  nuxt: {
    identifier: "nuxt",
    name: "Nuxt",
    genre: "web_framework",
    url: "https://www.nuxtjs.org",
    substrings: ["/_nuxt/"],
  },
  aweber: {
    identifier: "aweber",
    name: "AWeber",
    genre: "email",
    url: "https://www.aweber.com",
    spf_values: ["send.aweber.com", "fbl.optin.com"],
  },
  font_awesome: {
    identifier: "font_awesome",
    name: "Font Awesome",
    genre: "web_framework",
    url: "https://www.fontawesome.com",
    substrings: [
      "cdnjs.cloudflare.com/ajax/libs/font-awesome",
      "kit.fontawesome.com",
    ],
  },
  moosend: {
    identifier: "moosend",
    name: "Moosend",
    genre: "email",
    url: "https://www.moosend.com",
    spf_values: ["spfa.mailend.com"],
  },
  uptimerobot: {
    identifier: "uptimerobot",
    name: "UptimeRobot",
    genre: "monitoring",
    url: "https://www.uptimerobot.com",
    cname_values: ["stats.uptimerobot.com"],
  },
  oneuptime: {
    identifier: "oneuptime",
    name: "OneUptime",
    genre: "monitoring",
    url: "https://www.oneuptime.com",
    txt_values: ["oneuptime-verification"],
  },
  discord: {
    identifier: "discord",
    name: "Discord",
    genre: "social_media",
    url: "https://www.discord.com",
    urlSubstrings: ["discord.gg/"],
  },
  tiktok_pixel: {
    identifier: "tiktok_pixel",
    name: "TikTok Pixel",
    genre: "analytics",
    url: "https://www.tiktok.com",
    substrings: ["TiktokAnalyticsObject"],
  },
  tiktok: {
    identifier: "tiktok",
    name: "TikTok",
    genre: "social_media",
    url: "https://www.tiktok.com",
    icon: <Icon.TikTok className="size-6" />,
    urlSubstrings: ["tiktok.com"],
  },
  greenhouse: {
    identifier: "greenhouse",
    name: "Greenhouse",
    genre: "ats",
    url: "https://www.greenhouse.io",
    substrings: ["greenhouse.io"],
    spf_values: ["mg-spf.greenhouse.io"],
  },
  netsuite: {
    identifier: "netsuite",
    name: "NetSuite",
    genre: "crm",
    url: "https://www.netsuite.com",
    spf_values: ["mailsenders.netsuite.com"],
  },
  instagram: {
    identifier: "instagram",
    name: "Instagram",
    genre: "social_media",
    url: "https://www.instagram.com",
    icon: <Icon.Instagram className="size-6" />,
    urlSubstrings: ["instagram.com"],
  },
  facebook: {
    identifier: "facebook",
    name: "Facebook",
    genre: "social_media",
    url: "https://www.facebook.com",
    icon: <Icon.Facebook className="size-6" />,
    urlSubstrings: ["facebook.com", "facebook.com/groups"],
  },
  pardot: {
    identifier: "pardot",
    name: "Pardot",
    genre: "marketing",
    url: "https://www.pardot.com",
    spf_values: ["aspmx.pardot.com"],
  },
  linear: {
    identifier: "linear",
    name: "Linear",
    genre: "support",
    url: "https://www.linear.app",
    txt_values: ["linea-domain-verification"],
  },
  linkedin: {
    identifier: "linkedin",
    name: "LinkedIn",
    genre: "social_media",
    url: "https://www.linkedin.com",
    icon: <Icon.LinkedIn className="size-6" />,
    urlSubstrings: [
      "linkedin.com/company",
      "linkedin.com/school",
      "linkedin.com",
      "linkedin.com/in",
    ],
  },
  linkedin_ads: {
    identifier: "linkedin_ads",
    name: "LinkedIn Ads",
    genre: "marketing",
    url: "https://www.linkedin.com",
    icon: <Icon.LinkedIn className="size-6" />,
    substrings: ["ads.linkedin.com"],
  },
  hugo: {
    identifier: "hugo",
    name: "Hugo",
    genre: "static_site_generator",
    url: "https://gohugo.io",
    substrings: ['content="Hugo'],
  },
  fuse: {
    identifier: "fuse",
    name: "Fuse",
    genre: "search",
    url: "https://www.fusejs.io",
    substrings: ["/fuse.js"],
  },
  typekit: {
    identifier: "typekit",
    name: "Typekit",
    genre: "web_framework",
    url: "https://typekit.com",
    substrings: ["typekit.net"],
  },
  youtube: {
    identifier: "youtube",
    name: "YouTube",
    genre: "social_media",
    url: "https://www.youtube.com",
    icon: <Icon.YouTube className="size-6" />,
    urlSubstrings: ["youtube.com", "youtube.com/c", "youtube.com/channel"],
  },
  hashicorp: {
    identifier: "hashicorp",
    name: "HashiCorp",
    genre: "hosting",
    url: "https://www.hashicorp.com",
    txt_values: ["hcp-domain-verification"],
  },
  afterpay: {
    identifier: "afterpay",
    name: "Afterpay",
    genre: "payments",
    url: "https://www.afterpay.com",
    substrings: ["js.afterpay.com"],
  },
  stackadapt: {
    identifier: "stackadapt",
    name: "StackAdapt",
    genre: "marketing",
    url: "https://www.stackadapt.com",
    substrings: ["srv.stackadapt.com"],
  },
  google_fonts: {
    identifier: "google_fonts",
    name: "Google Fonts",
    genre: "web_framework",
    url: "https://fonts.google.com",
    substrings: ["fonts.googleapis.com"],
  },
  chrome_webstore: {
    identifier: "chrome_webstore",
    name: "Chrome Web Store",
    genre: "marketing",
    url: "https://chrome.google.com/webstore",
    substrings: ["chrome-webstore-item"],
  },
  iubenda: {
    identifier: "iubenda",
    name: "Iubenda",
    genre: "gdpr",
    url: "https://www.iubenda.com",
    substrings: ["cdn.iubenda.com"],
  },
  foundry: {
    identifier: "foundry",
    name: "Foundry",
    genre: "analytics",
    url: "https://www.foundryco.com",
    substrings: ["triblio.io"],
  },
  laravel: {
    identifier: "laravel",
    name: "Laravel",
    genre: "web_framework",
    substrings: ["livewireScriptConfig"],
    url: "https://www.laravel.com",
  },
  firebase: {
    identifier: "firebase",
    name: "Firebase",
    genre: "web_framework",
    url: "https://firebase.google.com",
    substrings: ["gstatic.com/firebasejs"],
    spf_values: ["_spf.firebasemail.com"],
  },
  cookiefirst: {
    identifier: "cookiefirst",
    name: "CookieFirst",
    genre: "gdpr",
    url: "https://www.cookiefirst.com",
    substrings: ["cookiefirst.com"],
  },
  yottaa: {
    identifier: "yottaa",
    name: "Yottaa",
    genre: "cdn",
    url: "https://www.yottaa.com",
    substrings: ["cdn.yottaa.com"],
  },
  cookielaw: {
    identifier: "cookielaw",
    name: "Cookie Law",
    genre: "gdpr",
    url: "https://www.cookielaw.org",
    substrings: ["cdn.cookielaw.org"],
  },
  hubspot: {
    identifier: "hubspot",
    name: "HubSpot",
    genre: "marketing",
    url: "https://www.hubspot.com",
    substrings: ["hs-scripts.com", "hs-banner.com", "hs-script-loader"],
    txt_values: [
      "hubspot-domain-verification",
      "hubspot-developer-verification",
    ],
  },
  github: {
    identifier: "github",
    name: "GitHub",
    genre: "social_media",
    url: "https://www.github.com",
    icon: <Icon.GitHub className="size-6" />,
    urlSubstrings: ["github.com", "github.com/[a-z]*"],
  },
  snapchat: {
    identifier: "snapchat",
    name: "Snapchat",
    genre: "social_media",
    url: "https://www.snapchat.com",
    urlSubstrings: ["snapchat.com"],
  },
  pinterest: {
    identifier: "pinterest",
    name: "Pinterest",
    genre: "social_media",
    url: "https://www.pinterest.com",
    icon: <Icon.Pinterest className="size-6" />,
    urlSubstrings: ["pinterest.com"],
  },
  reddit: {
    identifier: "reddit",
    name: "Reddit",
    genre: "social_media",
    url: "https://www.reddit.com",
    urlSubstrings: ["reddit.com"],
  },
  patreon: {
    identifier: "patreon",
    name: "Patreon",
    genre: "social_media",
    url: "https://www.patreon.com",
    urlSubstrings: ["patreon.com"],
  },
  outseta: {
    identifier: "outseta",
    name: "Outseta",
    genre: "payments",
    url: "https://www.outseta.com",
    substrings: ["cdn.outseta.com"],
  },
  segment: {
    identifier: "segment",
    name: "Segment",
    genre: "analytics",
    url: "https://www.segment.com",
    substrings: ["cdn.segment.com"],
  },
  apple_pay: {
    identifier: "apple_pay",
    name: "Apple Pay",
    genre: "payments",
    url: "https://www.apple.com/apple-pay",
    substrings: ["apple-pay-shop-capabilities"],
  },
  optinmonster: {
    identifier: "optinmonster",
    name: "OptinMonster",
    genre: "marketing",
    url: "https://www.optinmonster.com",
    substrings: ["cdn.omtrdc.net", "omappapi.com"],
  },
  chatbase: {
    identifier: "chatbase",
    name: "Chatbase",
    genre: "support",
    url: "https://www.chatbase.com",
    substrings: ["chatbase.co/embed.min.js"],
  },
  framer: {
    identifier: "framer",
    name: "Framer",
    genre: "hosting",
    url: "https://www.framer.com",
    substrings: ["Built with Framer"],
  },
  bubble: {
    identifier: "bubble",
    name: "Bubble",
    genre: "hosting",
    url: "https://www.bubble.io",
    substrings: ["bubble_page_load_id"],
  },
  convertkit: {
    identifier: "convertkit",
    name: "ConvertKit",
    genre: "email",
    url: "https://www.convertkit.com",
    substrings: [
      "filekitcdn.com",
      "/convertkit/",
      "f.convertkit.com",
      "app.convertkit.com",
      ".ck.page",
    ],
  },
  sparkpost: {
    identifier: "sparkpost",
    name: "SparkPost",
    genre: "email",
    url: "https://www.sparkpost.com",
    spf_values: ["sparkpostmail.com"],
  },
  formspark: {
    identifier: "formspark",
    name: "Formspark",
    genre: "form",
    url: "https://www.formspark.io",
    substrings: ["submit-form.io"],
  },
  formkeep: {
    identifier: "formkeep",
    name: "FormKeep",
    genre: "form",
    url: "https://www.formkeep.com",
    substrings: ["formkeep.com/f"],
  },
  revue: {
    identifier: "revue",
    name: "Revue",
    genre: "email",
    url: "https://www.getrevue.co",
    substrings: ["revue-form"],
    defunct: true,
  },
  tinyletter: {
    identifier: "tinyletter",
    name: "TinyLetter",
    genre: "email",
    url: "https://www.tinyletter.com",
    substrings: ['action="https://tinyletter.com'],
    defunct: true,
  },
  migadu: {
    identifier: "migadu",
    name: "Migadu",
    genre: "email",
    url: "https://www.migadu.com",
    txt_values: ["hosted-email-verify"],
    spf_values: ["spf.migadu.com"],
  },
  famewall: {
    identifier: "famewall",
    name: "Famewall",
    genre: "marketing",
    url: "https://www.famewall.com",
    substrings: ["famewall-embed"],
  },
  buysellads: {
    identifier: "buysellads",
    name: "BuySellAds",
    genre: "ads",
    url: "https://www.buysellads.com",
    substrings: ["servedby-buysellads.com"],
  },
  rebuy_engine: {
    identifier: "rebuy_engine",
    name: "Rebuy Engine",
    genre: "ecommerce",
    url: "https://www.rebuyengine.com",
    substrings: ["cdn.rebuyengine.com"],
  },
  omega_commerce: {
    identifier: "omega_commerce",
    name: "Omega Commerce",
    genre: "ecommerce",
    url: "https://www.omegacommerce.com",
    substrings: ["omegacommerce.com"],
  },
  northbeam: {
    identifier: "northbeam",
    name: "Northbeam",
    genre: "analytics",
    url: "https://www.northbeam.io",
    substrings: ["j.northbeam.io"],
  },
  506: {
    identifier: "506",
    name: "506",
    genre: "ecommerce",
    url: "https://www.506.io",
    substrings: ["506.io"],
  },
  protonmail: {
    identifier: "protonmail",
    name: "ProtonMail",
    genre: "email",
    url: "https://www.protonmail.com",
    spf_values: ["_spf.protonmail.ch"],
    txt_values: ["protonmail-verification"],
  },
  maxio: {
    identifier: "maxio",
    name: "Maxio",
    genre: "accounting",
    url: "https://www.maxio.com",
    spf_values: ["mailer.chargify.com"],
  },
};
