import Icon from "@/components/Icon";

type Genre =
  | "analytics"
  | "email"
  | "cdn"
  | "hosting"
  | "marketing"
  | "cms"
  | "web_framework"
  | "ecommerce"
  | "payments"
  | "support"
  | "ats"
  | "gdpr"
  | "calendar"
  | "form"
  | "podcast"
  | "monitoring"
  | "crm"
  | "everything"
  | "design"
  | "security"
  | "dns"
  | "videos"
  | "social_media";

type Service = {
  identifier: string;
  name: string;
  genre: Genre;
  url: string;
  icon?: React.ReactNode;
  cname_values?: string[];
  mx_values?: string[];
  ns_values?: string[];
  txt_values?: string[];
  spf_values?: string[];
  urlSubstrings?: string[];
  substrings?: string[];
  defunct?: boolean;
};

export const REGISTRY: {
  [key: string]: Service;
} = {
  github_pages: {
    identifier: "github_pages",
    name: "GitHub Pages",
    genre: "hosting",
    url: "https://pages.github.com",
    cname_values: ["pages.github.com"],
  },
  gitbook: {
    identifier: "gitbook",
    name: "GitBook",
    genre: "hosting",
    url: "https://www.gitbook.com",
    cname_values: ["gitbook.io"],
  },
  substack: {
    identifier: "substack",
    name: "Substack",
    url: "https://www.substack.com",
    genre: "email",
    cname_values: ["substack-custom-domains.com"],
  },
  umami: {
    identifier: "umami",
    name: "Umami",
    url: "https://umami.is",
    genre: "analytics",
    cname_values: ["umami.sh"],
    substrings: ["data-website-id"],
  },
  fastmail: {
    identifier: "fastmail",
    name: "FastMail",
    url: "https://www.fastmail.com",
    genre: "email",
    mx_values: ["smtp.messagingengine.com"],
    spf_values: ["spf.messagingengine.com"],
  },
  dnsimple: {
    identifier: "dnsimple",
    name: "DNSimple",
    url: "https://www.dnsimple.com",
    genre: "dns",
    ns_values: ["dnsimple.com"],
  },
  vercel: {
    identifier: "vercel",
    name: "Vercel",
    url: "https://www.vercel.com",
    genre: "hosting",
    ns_values: ["vercel-dns.com"],
  },
  wix: {
    identifier: "wix",
    name: "Wix",
    url: "https://www.wix.com",
    genre: "hosting",
    ns_values: ["wixdns.net"],
    substrings: ["Wix.com Website Builder"],
  },
  drip: {
    identifier: "drip",
    name: "Drip",
    url: "https://www.drip.com",
    genre: "email",
    substrings: ["data-drip"],
  },
  zoho_mail: {
    identifier: "zoho_mail",
    name: "Zoho Mail",
    url: "https://www.zoho.com/mail",
    genre: "email",
    mx_values: ["mx.zoho.com"],
    spf_values: ["zoho.com", "zeptomail.net"],
  },
  aws_ses: {
    identifier: "aws_ses",
    name: "AWS SES",
    url: "https://aws.amazon.com/ses",
    genre: "email",
    spf_values: ["amazonses.com"],
  },
  aws_cloudfront: {
    identifier: "aws_cloudfront",
    name: "AWS CloudFront",
    url: "https://aws.amazon.com/cloudfront/",
    genre: "cdn",
  },
  google_analytics: {
    identifier: "google_analytics",
    name: "Google Analytics",
    genre: "analytics",
    url: "https://analytics.google.com",
    substrings: ["GoogleAnalyticsObject"],
  },
  google_adsense: {
    identifier: "google_adsense",
    name: "Google AdSense",
    genre: "marketing",
    url: "https://www.google.com/adsense",
    substrings: ["adsbygoogle.js"],
  },
  cloudflare: {
    identifier: "cloudflare",
    name: "Cloudflare",
    genre: "cdn",
    url: "https://www.cloudflare.com",
    ns_values: ["cloudflare.com"],
    spf_values: ["_spf.mx.cloudflare.net"],
  },
  google_tag_manager: {
    identifier: "google_tag_manager",
    name: "Google Tag Manager",
    genre: "analytics",
    url: "https://tagmanager.google.com",
  },
  astro: {
    identifier: "astro",
    name: "Astro",
    genre: "web_framework",
    url: "https://astro.build",
    substrings: ["astro-slot"],
  },
  chargebee: {
    identifier: "chargebee",
    name: "Chargebee",
    genre: "payments",
    url: "https://www.chargebee.com",
    substrings: ["js.chargebee.com"],
  },
  mailchannels: {
    identifier: "mailchannels",
    name: "MailChannels",
    url: "https://www.mailchannels.com",
    genre: "email",
    spf_values: ["relay.mailchannels.net"],
  },
  meltwater: {
    identifier: "meltwater",
    name: "Meltwater",
    url: "https://www.meltwater.com",
    genre: "marketing",
    spf_values: ["meltwater.com"],
  },
  mailchimp: {
    identifier: "mailchimp",
    name: "Mailchimp",
    url: "https://mailchimp.com",
    genre: "email",
    substrings: ["list-manage.com", "mc:edit"],
    spf_values: ["servers.mcsv.net"],
  },
  clearbit: {
    identifier: "clearbit",
    name: "Clearbit",
    url: "https://clearbit.com",
    genre: "analytics",
    substrings: ["tag.clearbitscripts"],
  },
  sparkloop: {
    identifier: "sparkloop",
    name: "SparkLoop",
    url: "https://sparkloop.app",
    genre: "email",
    substrings: ["sparkloop.app"],
  },
  sendowl: {
    identifier: "sendowl",
    name: "SendOwl",
    url: "https://www.sendowl.com",
    genre: "ecommerce",
    substrings: ["https://transactions.sendowl.com/assets/sendowl.js"],
  },
  sendgrid: {
    identifier: "sendgrid",
    name: "SendGrid",
    genre: "email",
    url: "https://sendgrid.com",
    spf_values: ["sendgrid.net"],
  },
  flodesk: {
    identifier: "flodesk",
    name: "Flodesk",
    genre: "email",
    url: "https://www.flodesk.com",
    substrings: ["view.flodesk.com"],
  },
  webmentions: {
    identifier: "webmentions",
    name: "Webmentions",
    genre: "social_media",
    url: "https://webmention.io",
    substrings: ['rel="webmention"'],
  },
  bluesky: {
    identifier: "bluesky",
    name: "BlueSky",
    genre: "social_media",
    url: "https://bsky.app",
    urlSubstrings: ["bsky.app/profile"],
  },
  fresh: {
    identifier: "fresh",
    name: "Fresh",
    genre: "web_framework",
    url: "https://fresh.deno.dev",
    substrings: ["__frsh"],
  },
  jquery: {
    identifier: "jquery",
    name: "jQuery",
    genre: "web_framework",
    url: "https://jquery.com",
    substrings: ["jquery.com"],
  },
  mailerlite: {
    identifier: "mailerlite",
    name: "MailerLite",
    genre: "email",
    url: "https://www.mailerlite.com",
    substrings: ["static.mailerlite.com"],
  },
  loom: {
    identifier: "loom",
    name: "Loom",
    genre: "videos",
    url: "https://www.loom.com",
    txt_values: ["loom-verification", "loom-site-verification"],
  },
  alpinejs: {
    identifier: "alpinejs",
    name: "Alpine.js",
    genre: "web_framework",
    url: "https://alpinejs.dev",
    substrings: ["x-on:click"],
  },
  gauges: {
    identifier: "gauges",
    name: "Gauges",
    genre: "analytics",
    url: "https://www.gaug.es",
    substrings: ["gaug.es"],
  },
  facebook_ads: {
    identifier: "facebook_ads",
    name: "Facebook Ads",
    genre: "marketing",
    url: "https://www.facebook.com/business/ads",
    txt_values: ["facebook-domain-verification"],
  },
  notion: {
    identifier: "notion",
    name: "Notion",
    genre: "design",
    url: "https://www.notion.so",
    txt_values: ["notion-domain-verification"],
  },
  facebook_pixel: {
    identifier: "facebook_pixel",
    name: "Facebook Pixel",
    genre: "analytics",
    url: "https://www.facebook.com/business/learn/facebook-ads-pixel",
    substrings: ["f.fbq"],
  },
  hackerone: {
    identifier: "hackerone",
    name: "HackerOne",
    genre: "security",
    url: "https://hackerone.com",
    txt_values: ["h1-domain-verification"],
  },
  ahrefs: {
    identifier: "ahrefs",
    name: "Ahrefs",
    genre: "marketing",
    url: "https://ahrefs.com",
    txt_values: ["ahrefs-site-verification"],
  },
  google_webmaster_tools: {
    identifier: "google_webmaster_tools",
    name: "Google Webmaster Tools",
    genre: "analytics",
    url: "https://www.google.com/webmasters/tools/home",
    txt_values: ["google-site-verification"],
  },
  senja: {
    identifier: "senja",
    name: "Senja",
    genre: "marketing",
    url: "https://www.senja.io",
    substrings: ["static.senja"],
  },
  crisp: {
    identifier: "crisp",
    name: "Crisp",
    genre: "support",
    url: "https://crisp.chat",
    substrings: ["CRISP_WEBSITE_ID"],
  },
  helpscout: {
    identifier: "helpscout",
    name: "Help Scout",
    genre: "support",
    url: "https://www.helpscout.com",
    spf_values: ["helpscoutemail.com"],
  },
  heroku: {
    identifier: "heroku",
    name: "Heroku",
    url: "https://www.heroku.com",
    genre: "hosting",
  },
  groove: {
    identifier: "groove",
    name: "Groove",
    url: "https://www.groovehq.com",
    genre: "support",
    substrings: [],
  },
  webflow: {
    identifier: "webflow",
    name: "Webflow",
    url: "https://www.webflow.com",
    genre: "web_framework",
    substrings: ["/js/webflow"],
  },
  loops: {
    identifier: "loops",
    name: "Loops",
    url: "https://www.loops.so",
    genre: "email",
    substrings: ["app.loops.so"],
  },
  netlify: {
    identifier: "netlify",
    name: "Netlify",
    url: "https://www.netlify.com",
    genre: "hosting",
  },
  fathom: {
    identifier: "fathom",
    name: "Fathom",
    url: "https://www.usefathom.com",
    genre: "analytics",
    substrings: ["cdn.usefathom.com"],
  },
  tally: {
    identifier: "tally",
    name: "Tally",
    url: "https://www.tally.so",
    genre: "form",
    substrings: ["tally.so"],
  },
  savvycal: {
    identifier: "savvycal",
    name: "SavvyCal",
    url: "https://www.savvycal.com",
    genre: "calendar",
    substrings: ["savvycal.com"],
  },
  transistor: {
    identifier: "transistor",
    name: "Transistor",
    url: "https://www.transistor.fm",
    genre: "podcast",
    substrings: [".transistor.fm"],
  },
  rewardful: {
    identifier: "rewardful",
    name: "Rewardful",
    url: "https://www.rewardful.com",
    genre: "marketing",
    substrings: [".getrewardful.com", "data-rewardful", "window,'rewardful'"],
  },
  php: {
    identifier: "php",
    name: "PHP",
    url: "https://www.php.net",
    genre: "web_framework",
  },
  shopify: {
    identifier: "shopify",
    name: "Shopify",
    url: "https://www.shopify.com",
    genre: "ecommerce",
  },
  rails: {
    identifier: "rails",
    name: "Ruby on Rails",
    url: "https://rubyonrails.org",
    genre: "web_framework",
    substrings: ["data-turbo"],
  },
  new_relic: {
    identifier: "new_relic",
    name: "New Relic",
    url: "https://www.newrelic.com",
    genre: "monitoring",
    substrings: ["newrelic.com"],
  },
  nextjs: {
    identifier: "nextjs",
    name: "Next.js",
    url: "https://www.nextjs.org",
    genre: "web_framework",
    substrings: ["_next/static"],
  },
  klaviyo: {
    identifier: "klaviyo",
    name: "Klaviyo",
    url: "https://www.klaviyo.com",
    genre: "email",
    txt_values: ["klaviyo-site-verification"],
    substrings: ["klaviyo.init"],
  },
  apollo: {
    identifier: "apollo",
    name: "Apollo",
    url: "https://www.apollo.io",
    genre: "analytics",
    substrings: ["assets.apollo.io"],
  },
  zendesk: {
    identifier: "zendesk",
    name: "Zendesk",
    url: "https://www.zendesk.com",
    genre: "support",
    txt_values: ["mail.zendesk.com"],
    substrings: ["zdassets.com"],
    spf_values: ["mail.zendesk.com"],
  },
  paddle: {
    identifier: "paddle",
    name: "Paddle",
    url: "https://www.paddle.com",
    genre: "payments",
    txt_values: ["paddle-verification"],
  },
  stripe: {
    identifier: "stripe",
    name: "Stripe",
    url: "https://www.stripe.com",
    genre: "payments",
    txt_values: ["stripe-verification"],
    substrings: ["js.stripe.com"],
  },
  beehiiv: {
    identifier: "beehiiv",
    name: "Beehiiv",
    url: "https://www.beehiiv.com",
    genre: "marketing",
    substrings: ["beehiiv.com"],
  },
  vwo: {
    identifier: "vwo",
    name: "Visual Website Optimizer",
    url: "https://www.vwo.com",
    genre: "marketing",
    substrings: ["_vwo_code"],
  },
  squarespace: {
    identifier: "squarespace",
    name: "Squarespace",
    url: "https://www.squarespace.com",
    genre: "cms",
    substrings: ["assets.squarespace.com"],
  },
  wordpress: {
    identifier: "wordpress",
    name: "WordPress",
    url: "https://www.wordpress.org",
    genre: "cms",
    substrings: ["wp-content/plugins"],
  },
  blogger: {
    identifier: "blogger",
    name: "Blogger",
    url: "https://www.blogger.com",
    genre: "cms",
    substrings: ['content="blogger" name="generator"'],
  },
  jekyll: {
    identifier: "jekyll",
    name: "Jekyll",
    url: "https://www.jekyllrb.com",
    genre: "web_framework",
    substrings: ['content="Jekyll'],
  },
  plausible: {
    identifier: "plausible",
    name: "Plausible",
    url: "https://www.plausible.io",
    genre: "analytics",
    substrings: ["plausible.io/js"],
  },
  whimsical: {
    identifier: "whimsical",
    name: "Whimsical",
    url: "https://www.whimsical.com",
    genre: "design",
    txt_values: ["whimsical="],
  },
  mixpanel: {
    identifier: "mixpanel",
    name: "Mixpanel",
    url: "https://www.mixpanel.com",
    genre: "analytics",
    txt_values: ["mixpanel-domain-verify"],
  },
  microsoft_clarity: {
    identifier: "microsoft_clarity",
    name: "Microsoft Clarity",
    url: "https://www.microsoft.com",
    genre: "analytics",
    substrings: ["c,l,a,r,i,t,y"],
  },
  buttondown: {
    identifier: "buttondown",
    name: "Buttondown",
    url: "https://www.buttondown.email",
    genre: "email",
  },
  intercom: {
    identifier: "intercom",
    name: "Intercom",
    url: "https://www.intercom.com",
    genre: "support",
    substrings: ["intercomSettings"],
  },
  gatsby: {
    identifier: "gatsby",
    name: "Gatsby",
    url: "https://www.gatsbyjs.com",
    genre: "web_framework",
    substrings: ['name="generator" content="Gatsby'],
  },
  ghost: {
    identifier: "ghost",
    name: "Ghost",
    url: "https://www.ghost.org",
    genre: "cms",
    substrings: ['name="generator" content="Ghost'],
  },
  hotjar: {
    identifier: "hotjar",
    name: "Hotjar",
    url: "https://www.hotjar.com",
    genre: "analytics",
    substrings: ["h,o,t,j,a,r"],
  },
  drift: {
    identifier: "drift",
    name: "Drift",
    url: "https://www.drift.com",
    genre: "support",
    txt_values: ["drift-domain-verification"],
  },
  mailgun: {
    identifier: "mailgun",
    name: "Mailgun",
    url: "https://www.mailgun.com",
    genre: "email",
    spf_values: ["mailgun.org", "spf.mandrillapp.com"],
  },
  campaign_monitor: {
    identifier: "campaign_monitor",
    name: "Campaign Monitor",
    url: "https://www.campaignmonitor.com",
    genre: "email",
    spf_values: ["_spf.createsend.com", "spf.createsend.com"],
  },
  google: {
    identifier: "google",
    name: "Google",
    url: "https://www.google.com",
    genre: "everything",
    spf_values: ["_spf.google.com"],
  },
  rollbar: {
    identifier: "rollbar",
    name: "Rollbar",
    url: "https://www.rollbar.com",
    genre: "monitoring",
    substrings: ["_rollbarConfig"],
  },
  postmark: {
    identifier: "postmark",
    name: "Postmark",
    url: "https://www.postmarkapp.com",
    genre: "email",
    spf_values: ["mtasv.net"],
  },
  posthog: {
    identifier: "posthog",
    name: "PostHog",
    url: "https://www.posthog.com",
    genre: "analytics",
    substrings: ["posthog.init"],
  },
  amplitude: {
    identifier: "amplitude",
    name: "Amplitude",
    url: "https://www.amplitude.com",
    genre: "analytics",
    substrings: ["amplitude.init", "e.amplitude"],
  },
  markmonitor: {
    identifier: "markmonitor",
    name: "MarkMonitor",
    url: "https://www.markmonitor.com",
    genre: "monitoring",
    spf_values: ["spfhost.messageprovider.com"],
  },
  marketo: {
    identifier: "marketo",
    name: "Marketo",
    url: "https://www.marketo.com",
    spf_values: ["mktomail.com"],
    substrings: ["bizible.com"],
    genre: "crm",
  },
  smtp2go: {
    identifier: "smtp2go",
    name: "SMTP2GO",
    url: "https://www.smtp2go.com",
    genre: "email",
    spf_values: ["spf.smtp2go.com"],
  },
  salesforce: {
    identifier: "salesforce",
    name: "Salesforce",
    url: "https://www.salesforce.com",
    genre: "crm",
    spf_values: ["_spf.salesforce.com"],
  },
  happyfox: {
    identifier: "happyfox",
    name: "HappyFox",
    genre: "support",
    spf_values: ["spf.happyfox.com"],
    url: "https://www.happyfox.com",
  },
  consider: {
    identifier: "consider",
    name: "Consider",
    url: "https://www.consider.com",
    genre: "ats",
    cname_values: ["boards.consider.com"],
  },
  svelte: {
    identifier: "svelte",
    name: "Svelte",
    url: "https://www.svelte.dev",
    genre: "web_framework",
    substrings: ["__svelte__", "__sveltekit"],
  },
  twitter: {
    identifier: "twitter",
    name: "Twitter",
    genre: "social_media",
    url: "https://www.twitter.com",
    icon: <Icon.Twitter className="size-6" />,
    urlSubstrings: ["twitter.com", "x.com"],
  },
  discord: {
    identifier: "discord",
    name: "Discord",
    genre: "social_media",
    url: "https://www.discord.com",
    urlSubstrings: ["discord.gg/"],
  },
  tiktok_pixel: {
    identifier: "tiktok_pixel",
    name: "TikTok Pixel",
    genre: "analytics",
    url: "https://www.tiktok.com",
    substrings: ["TiktokAnalyticsObject"],
  },
  tiktok: {
    identifier: "tiktok",
    name: "TikTok",
    genre: "social_media",
    url: "https://www.tiktok.com",
    icon: <Icon.TikTok className="size-6" />,
    urlSubstrings: ["tiktok.com"],
  },
  instagram: {
    identifier: "instagram",
    name: "Instagram",
    genre: "social_media",
    url: "https://www.instagram.com",
    icon: <Icon.Instagram className="size-6" />,
    urlSubstrings: ["instagram.com"],
  },
  facebook: {
    identifier: "facebook",
    name: "Facebook",
    genre: "social_media",
    url: "https://www.facebook.com",
    icon: <Icon.Facebook className="size-6" />,
    urlSubstrings: ["facebook.com", "facebook.com/groups"],
  },
  pardot: {
    identifier: "pardot",
    name: "Pardot",
    genre: "marketing",
    url: "https://www.pardot.com",
    spf_values: ["aspmx.pardot.com"],
  },
  linear: {
    identifier: "linear",
    name: "Linear",
    genre: "support",
    url: "https://www.linear.app",
    txt_values: ["linea-domain-verification"],
  },
  linkedin: {
    identifier: "linkedin",
    name: "LinkedIn",
    genre: "social_media",
    url: "https://www.linkedin.com",
    icon: <Icon.LinkedIn className="size-6" />,
    urlSubstrings: [
      "linkedin.com/company",
      "linkedin.com/school",
      "linkedin.com",
    ],
  },
  youtube: {
    identifier: "youtube",
    name: "YouTube",
    genre: "social_media",
    url: "https://www.youtube.com",
    icon: <Icon.YouTube className="size-6" />,
    urlSubstrings: ["youtube.com", "youtube.com/c", "youtube.com/channel"],
  },
  afterpay: {
    identifier: "afterpay",
    name: "Afterpay",
    genre: "payments",
    url: "https://www.afterpay.com",
    substrings: ["js.afterpay.com"],
  },
  stackadapt: {
    identifier: "stackadapt",
    name: "StackAdapt",
    genre: "marketing",
    url: "https://www.stackadapt.com",
    substrings: ["srv.stackadapt.com"],
  },
  chrome_webstore: {
    identifier: "chrome_webstore",
    name: "Chrome Web Store",
    genre: "marketing",
    url: "https://chrome.google.com/webstore",
    substrings: ["chrome-webstore-item"],
  },
  iubenda: {
    identifier: "iubenda",
    name: "Iubenda",
    genre: "gdpr",
    url: "https://www.iubenda.com",
    substrings: ["cdn.iubenda.com"],
  },
  foundry: {
    identifier: "foundry",
    name: "Foundry",
    genre: "analytics",
    url: "https://www.foundryco.com",
    substrings: ["triblio.io"],
  },
  laravel: {
    identifier: "laravel",
    name: "Laravel",
    genre: "web_framework",
    substrings: ["livewireScriptConfig"],
    url: "https://www.laravel.com",
  },
  firebase: {
    identifier: "firebase",
    name: "Firebase",
    genre: "web_framework",
    url: "https://firebase.google.com",
    substrings: ["gstatic.com/firebasejs"],
  },
  cookiefirst: {
    identifier: "cookiefirst",
    name: "CookieFirst",
    genre: "gdpr",
    url: "https://www.cookiefirst.com",
    substrings: ["cookiefirst.com"],
  },
  yottaa: {
    identifier: "yottaa",
    name: "Yottaa",
    genre: "cdn",
    url: "https://www.yottaa.com",
    substrings: ["cdn.yottaa.com"],
  },
  hubspot: {
    identifier: "hubspot",
    name: "HubSpot",
    genre: "marketing",
    url: "https://www.hubspot.com",
    substrings: ["hs-scripts.com", "hs-banner.com", "hs-script-loader"],
    txt_values: ["hubspot-domain-verification"],
  },
  github: {
    identifier: "github",
    name: "GitHub",
    genre: "social_media",
    url: "https://www.github.com",
    icon: <Icon.GitHub className="size-6" />,
    urlSubstrings: ["github.com"],
  },
  snapchat: {
    identifier: "snapchat",
    name: "Snapchat",
    genre: "social_media",
    url: "https://www.snapchat.com",
    urlSubstrings: ["snapchat.com"],
  },
  pinterest: {
    identifier: "pinterest",
    name: "Pinterest",
    genre: "social_media",
    url: "https://www.pinterest.com",
    icon: <Icon.Pinterest className="size-6" />,
    urlSubstrings: ["pinterest.com"],
  },
  reddit: {
    identifier: "reddit",
    name: "Reddit",
    genre: "social_media",
    url: "https://www.reddit.com",
    urlSubstrings: ["reddit.com"],
  },
  patreon: {
    identifier: "patreon",
    name: "Patreon",
    genre: "social_media",
    url: "https://www.patreon.com",
    urlSubstrings: ["patreon.com"],
  },
  outseta: {
    identifier: "outseta",
    name: "Outseta",
    genre: "payments",
    url: "https://www.outseta.com",
    substrings: ["cdn.outseta.com"],
  },
  segment: {
    identifier: "segment",
    name: "Segment",
    genre: "analytics",
    url: "https://www.segment.com",
    substrings: ["cdn.segment.com"],
  },
  optinmonster: {
    identifier: "optinmonster",
    name: "OptinMonster",
    genre: "marketing",
    url: "https://www.optinmonster.com",
    substrings: ["cdn.omtrdc.net", "omappapi.com"],
  },
  chatbase: {
    identifier: "chatbase",
    name: "Chatbase",
    genre: "support",
    url: "https://www.chatbase.com",
    substrings: ["chatbase.co/embed.min.js"],
  },
  framer: {
    identifier: "framer",
    name: "Framer",
    genre: "hosting",
    url: "https://www.framer.com",
    substrings: ["Built with Framer"],
  },
  bubble: {
    identifier: "bubble",
    name: "Bubble",
    genre: "hosting",
    url: "https://www.bubble.io",
    substrings: ["bubble_page_load_id"],
  },
  convertkit: {
    identifier: "convertkit",
    name: "ConvertKit",
    genre: "email",
    url: "https://www.convertkit.com",
    substrings: ["filekitcdn.com", "/convertkit/"],
  },
  sparkpost: {
    identifier: "sparkpost",
    name: "SparkPost",
    genre: "email",
    url: "https://www.sparkpost.com",
    spf_values: ["sparkpostmail.com"],
  },
  formspark: {
    identifier: "formspark",
    name: "Formspark",
    genre: "form",
    url: "https://www.formspark.io",
    substrings: ["submit-form.io"],
  },
  revue: {
    identifier: "revue",
    name: "Revue",
    genre: "email",
    url: "https://www.getrevue.co",
    substrings: ["revue-form"],
    defunct: true,
  },
  tinyletter: {
    identifier: "tinyletter",
    name: "TinyLetter",
    genre: "email",
    url: "https://www.tinyletter.com",
    substrings: ['action="https://tinyletter.com'],
    defunct: true,
  },
  migadu: {
    identifier: "migadu",
    name: "Migadu",
    genre: "email",
    url: "https://www.migadu.com",
    txt_values: ["hosted-email-verify"],
    spf_values: ["spf.migadu.com"],
  },
};
